mysite/food/urls.py
from . import views
from django.urls import path

app_name='food'
urlpatterns = [
    #/food/
    path('',views.IndexClassView.as_view(),name='index'),
    #/food/3
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('item/', views.item,name='item'),
    #add items
    path('add',views.CreateItem.as_view(),name='create_item'),
    #edit items
    path('update/<int:id>/',views.update_item,name='update_item'),
    #delete item
    path('delete/<int:id>',views.delete_item,name='delete_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static



#from mysite import users

urlpatterns = [
    path('admin/',admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.urls import reverse

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name
    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500)


# get_absolute_url es para crear una página de detalles del objeto
# Aquí get_absolute_url viene en imagen.
# Le dice a Django dónde ir cuando se crea una nueva publicación.


    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location=models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_desc','item_price','item_image']

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=['username','email','password1','password2']

mysite/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse

from .forms import ItemForm
from .models import Item
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.
# def index(request):
#     item_list=Item.objects.all()
#     #template=loader.get_template('food/index.html')
#     context={
#         'item_list':item_list,
#     }
#     return render(request,'food/index.html',context)


#presenta toda la lista
class IndexClassView(ListView):
    model=Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'



def item(request):
    return HttpResponse('This is an item view')

# def detail(request,item_id):
#     item=Item.objects.get(pk=item_id)
#     context={
#         'item':item,
#     }
#     return render(request,'food/detail.html',context)

# Presenta los detalles
class FoodDetail(DetailView):
    model=Item
    template_name = 'food/detail.html'


def create_item(request):
    form=ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

#Sirve para crear registros o guardarlos
class CreateItem(CreateView):
    model=Item;
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name=self.request.user

        return super().form_valid(form)


def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item=Item.objects.get(id=id)

    if request.method=='POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/item-delete.html',{'item':item})

mysite/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.

def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is saved')
            return redirect('login')
    else:
        form=RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">



</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
         <a href="#" class="navbar-brand">FoodApp</a>
        <div class="navbar menu">
            <a class="nav-item nav-link" href={% url 'food:create_item' %}>Add Item</a>
            <a class="nav-item nav-link">Delete Item</a>
            <a class="nav-item nav-link">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}

        </div>
    </nav>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tag}}">{{message}}</div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}

</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{ item.item_image }}" class="card" alt="">
        </div>
        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>${{ object.item_price }}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete Item</a>
        </div>
    </div>
</div>

{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html>
<title>Page Title</title>
</head>
<body>

{% block body %}
 {% for item in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2 py-5">
            <img class="card" height="150px" height="150px" src="{{item.item_image}}"/>
        </div>
        <div class="col-md-4 py-5">
            <h3>{{item.item_name}}</h3>
            <h3>{{item.item_desc}}</h3>
            <h3>${{item.item_price}}</h3>
            <h3>{{item.user_name}}</h3>
        </div>
        <div class="col-md-2 py-5">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>


 {% endfor %}
{% endblock %}

This is the old code

    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food App</a>
            <div class="navbar">
                <a href="#" class="nav-item nav-link">Add Item</a>
                <a href="#" class="nav-item nav-link">Delete Item</a>
                <a href="#" class="nav-item nav-link">View Item</a>
            </div>
    </nav>


    <ul>
        <li>
            <a href="">{{item.id}}--{{item.item_name}}</a>
        </li>
    </ul>
</body>
</html>



<!--
 {% for item in item_list %}
    <ul>
        <li>
            <a href="{% url 'food:detail' item.id %}">{{item.id}}&#45;&#45; {{item.item_name}}</a>
        </li>
    </ul>
  {% endfor %}-->

mysite/food/templates/food/item-delete.html
<form method="POST">

    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info text-white">
          <div class="card-title">
            Register
          </div>
        </div>
      </div>
      <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {{form}}
            <button type="submit">Add</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mysite/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info text-white">
          <div class="card-title">
            Login
          </div>
        </div>
      </div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group">
                {{ field.name }}
                {{ field }}
            </div>
          {% endfor %}
          <button class="btn-info" type="submit">Login</button>
        </form>
      </div>
    </div>
  </div>
</div>




{% endblock %}

mysite/users/templates/users/logout.html
<h1>You Have Been Logout</h1>

mysite/users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{ user.profile.image.url }}" alt="">

mysite/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info text-white">
          <div class="card-title">
            Register
          </div>
        </div>
      </div>
      <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.name }}
                    <br>
                    {{ field }}
                </div>
            {% endfor %}
            <button class="btn-info" type="submit">Register</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}